### ISSUE TITLE
Original Faces and LGNPC

### ISSUE THREAD

**Issue by Jaiysaun** [mlox/mlox#10]
Minor load order suggestion. Sorry if this is in the wrong place.
Original Faces by ARHIZ (Original Faces 1.3.esp) seems to cause a syntax error if loaded after LGNPC Gnaar Mok (LGNPC_GnaarMok_v1_20.esp) and might also cause similar problems with other LGNPC mods. Placing it before the LGNPC mods fixed the problem.

**Comment by Dragon-32** [comment]
@Translator5 - Could you read and follow the [Guidelines for Editors of the mlox rule-base](https://github.com/mlox/mlox/blob/master/Documentation/Editing%20Guidelines.md)?

Your recent rules have caused [cycle errors](https://forums.nexusmods.com/index.php?/topic/1314413-mlox/?p=51987437)

You're also just adding rules to the end, not following syntax for naming (so finding the rules you've added in a few months time will be hard) and using the ANY predicate in Order rules which, unless the code's changed, doesn't work (AFAIK).

**Comment by Dragon-32** [comment]
Rules for Original Faces added into latest released version of mlox rule-set ("[Version 2017-08-03 18:33:33 (UTC)]")
