### ISSUE TITLE
Don't use UTF-8-BOM encoding for mlox_base.txt

### ISSUE THREAD

**Issue by Dragon-32** [mlox/mlox#18]
Error:
mlox_base.txt:1: Parse Error(), expected start of rule [Buffer=ï»¿;; -*- mode: emacs-lisp -*-

Version of wxPython (I guess) used by mlox can't parse UTF-8-BOM

Nexus error report:
https://forums.nexusmods.com/index.php?/topic/1314413-mlox/?p=53486548

Looks like plain old UTF-8 works.

@Translator5 - for info.

**Comment by EmperorArthur** [comment]
I'd like to move to Python 3 sometime soon.

The downside of such a move is Python is much more strict about encodings.  The upside is Python is much more strict about encodings.

**Comment by Translator5** [comment]
got it
