### ISSUE TITLE
wxPython 3.0.2.0

### ISSUE THREAD

**Issue by Dragon-32** [mlox/mlox#5]
I've been running mlox with Python 2.7.12 and wxPython 3.0.2.0

Works fine apart from one thing I've noticed. It's not possible to paste a mod list into the Active Plugins window

If I'm looking to run mlox against another user's posted mod list I have to save that list to a new TXT file and load that (Active Plugins pane > Right click > Open File).

No biggie and breaking support for wxPython 2.8.12.1 wouldn't be a good thing to happen (pretty sure that both Wrye Mash and Wrye Bash use the ANSI version of that).

Very much a nice-to-have.

**Comment by EmperorArthur** [comment]
"Fixed" by moving from wxPython to PyQt5.
