### ISSUE TITLE
Some issues with my mlox report

### ISSUE THREAD

**Issue by MacBone** [mlox/mlox#8]
[PATCH]
 !!'MISSING(GH PEC Patch.ESP)' for:
 [ALL
   '[VER > 1.2 graphic herbalism.esp]',
   'Pearls Enhanced - Colored Pearls Add-on.ESP']
 | "[Skrawafunda's "Graphic Herbalism Pearls Enhanced Patch"] is a compatibility patch for Graphic Herbalism and Pearls Enhanced. It allows you to collect all the new pearls from collops witout having to "open" them. In other words, this patch updates herbalism scripts to include the precious additions from Pearls Enhanced."
 | (Ref: "Graphic Herbalism Pearls Enhanced Patch Readme.txt")
 | Download "Graphic Herbalism Pearls Enhanced Patch" by Skrawafunda from Morrowind Nexus: http://www.nexusmods.com/morrowind/mods/43236/

However, I am running the patch, "GHE PEC Patch.ESP".  It looks like it has an incorrect name in mlox.

[REQUIRES]
 !!![ALL 'mel_teleportPlugin_1_3.esp', 'BT_Whitewolf_2_0.esm'] Requires:
 > 'MISSING(mel_teleportPlugin_1_3_Patches.esp)'
 | "mel_teleportPlugin_1_3_Patches.esp" patches the companions from Emma's "The White Wolf of the Lokken Mountain", Qarl's "The Underground" and Emma's "Laura Craft Romance and Adventure mod" so that they are compatible with "Melian's Teleport Mod"
 | (Ref: mel_tpp_1_3_readme.html)
 | [Note that you may see this message if you have an older version of one
 | of the pre-requisites. In that case, it is suggested that you upgrade
 | to the newer version].

Although Emma's site says there is a newer version of BT_Whitewolf_2_0.esm, the download on the site is for the 2.0 version of the mod.

[CONFLICT]
 > 'wl_SolstheimOverhaul_v1.esm'
 > [ANY 'BT_Whitewolf_2_0.esm', 'MISSING(BT_Whitewolf_2_0.esp)']
 | The readme for Wollibeebee's "Solstheim: Tomb of the Snow Prince" promises a patch for Emma's "White Wolf of Lokken" but one is not available. It is safe to conclude that the two mods conflict.
 | (Ref: "STOTSP 1 2-42979-1-2.7z\Readme.rtf")

A patch exists called "Lokken-STOTSP Patch.ESP" available here:  http://www.nexusmods.com/morrowind/mods/44575/?.  It comes with a modified version of BT_Whitewolf_2_0.esm for compatibility.

[NOTE]
 > [ANY
 >   '[SIZE !3829352 BT_Whitewolf_2_0.esm]',
 >   '[SIZE !3829352 BT_Whitewolf_2_0.esp]']
 | ! The latest version of White Wolf of Lokken is 2.1, which includes Children of Morrowind 2.0 and the "kiss patch". You may want to upgrade:
 | ! http://lovkullen.net/Emma/lokken.htm

Emma's site says the download version of BT_Whitewolf is 2.1, but when downloaded, the file is 2.0.  The same is true for the file when downloaded from GHF.

**Comment by Dragon-32** [comment]
GH PEC Patch.ESP
I think you're not running "Graphic Herbalism Extra.esp" so you should be running "GH PEC Patch.ESP" not "GHE PEC Patch.ESP"

mel_teleportPlugin_1_3.esp
You're not running "mel_teleportPlugin_1_3_Patches.esp" which patches Lokken companions.

wl_SolstheimOverhaul_v1.esm
Thanks for the link

BT_Whitewolf_2_0.esm
There's nothing beyond file size to distinguish 2.0 and 2.1, if you've cleaned the 2.1 files with TESTool / tes3cmd then, well, they'll be a different file size.

**Comment by MacBone** [comment]
Thanks for your response!  Very helpful.  =)

I'm running Graphic Herbalism Extra (Correct UV).esp, rather than Graphic Herbalism Extra.esp.

**Comment by Dragon-32** [comment]
Ah. I think I need a NOT rule in one of those then. Graphic Herbalism mods and patches are bugger complicated...

**Comment by Dragon-32** [comment]
Got changes (where needed) for all of these locally, should find their way into the next release of the rule-set

**Comment by EmperorArthur** [comment]
With Pull #12 merged, can this be closed?

**Comment by Dragon-32** [comment]
I guess so, if we're not waiting for the updated mlox rules to be released.

**Comment by EmperorArthur** [comment]
Latest mlox_base has been released!!!

Closing this issue.
